AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ClassVars:
  Description: 'Avoid the use of class variables.'
  Enabled: false

