AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Enabled: 300

Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ClassVars:
  Description: 'Avoid the use of class variables.'
  Enabled: false

Metrics/MethodLength:
  Max: 50

Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
