sudo: false
language: ruby
rvm:
  - 2.3.4

services:
  - mysql
  - redis-server

cache:
  - bundler

before_install:
  - gem install bundler
  - bundle install --path vendor/bundle

script:
  - bundle exec rake
  - cd tests
  - echo `pwd`
  - bundle install
  - bundle exec cucumber