sudo: false
language: ruby
rvm:
  - 2.3.4

services:
  - mysql
  - redis-server

cache:
  - bundler

before_install:
  - bundle install
  - gem install dotenv
  - ruby firebase_json_generator.rb

script:
  - bundle exec rake
  - cd tests
  - export BUNDLE_GEMFILE=Gemfile
  - bundle install
  - bundle exec cucumber