sudo: false
language: ruby
rvm:
  - 2.3.4

services:
  - mysql
  - redis-server

cache:
  directories:
    - /home/travis/.rvm/

before_install:
  - gem install bundler
  - bundle install --path vendor/bundle

script:
  - cd spec
  - bundle exec rake
  - cd ../tests
  - bundle exec cucumber