sudo: false
language: ruby
rvm:
- 2.5.0
services:
- mysql
- redis-server
cache:
- bundler
before_install:
- openssl aes-256-cbc -K $encrypted_4dc905cf70c6_key -iv $encrypted_4dc905cf70c6_iv
  -in tests/firebase_key -out tests/firebase_key.json -d
- bundle install
- gem install dotenv
script:
- bundle exec rake
- cd tests
- export BUNDLE_GEMFILE=Gemfile
- bundle install
- bundle exec cucumber
